#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 29 20:04:22 BST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=
